const ODIN_LESSON_GENERATOR = {
  lastHtml: "",

  esc(text){
    return String(text || "")
      .replaceAll("&","&amp;")
      .replaceAll("<","&lt;")
      .replaceAll(">","&gt;");
  },

  getSessionSummary(){
    const files = ODIN_SESSION.get();
    const byKind = {};
    files.forEach(f => {
      const k = f.kind || "DOCUMENT";
      if(!byKind[k]) byKind[k] = [];
      byKind[k].push(f.title);
    });
    return { files, byKind };
  },

  validateSession(files){
    const warnings = [];
    const hasTemplate = files.some(f => f.path.includes("TEMPLATE_BASE_v1.html"));
    const hasQA = files.some(f => (f.kind || "").includes("QA"));
    const hasTranslation = files.some(f => (f.kind || "").includes("TRANSLATION"));

    if(!hasTemplate) warnings.push("TEMPLATE_BASE_v1.html не знайдено в SESSION.");
    if(!hasQA) warnings.push("QA файли не знайдені в SESSION.");
    if(!hasTranslation) warnings.push("TRANSLATION файли не знайдені в SESSION.");

    return warnings;
  },

  generate(){
    const topic = document.getElementById("lessonTopic").value.trim() || "ODIN Lesson";
    const task = document.getElementById("lessonTask").value.trim() || "Створити урок.";
    const {files, byKind} = this.getSessionSummary();
    const warnings = this.validateSession(files);
    const now = new Date().toISOString();

    const fileList = files.map(f => `<li><b>${this.esc(f.kind || "DOCUMENT")}</b> — ${this.esc(f.title)}<br><small>${this.esc(f.path)}</small></li>`).join("\n");

    const sessionBlocks = Object.entries(byKind).map(([kind, names]) => `
      <h3>${this.esc(kind)}</h3>
      <ul>${names.map(n => `<li>${this.esc(n)}</li>`).join("")}</ul>
    `).join("\n");

    const qaStatus = warnings.length ? "QA_PASSED_WITH_WARNINGS" : "QA_PASSED";

    this.lastHtml = `<!doctype html>
<html lang="uk">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${this.esc(topic)}</title>
<style>
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:0;background:#f5f7fb;color:#132033;line-height:1.6}
header{position:sticky;top:0;background:#0f172a;color:white;padding:16px 20px;z-index:5}
main{max-width:980px;margin:0 auto;padding:20px}
section{background:white;border:1px solid #dbe5f2;border-radius:22px;padding:18px;margin:16px 0;box-shadow:0 10px 28px rgba(15,23,42,.06)}
.badge{display:inline-block;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-weight:800;padding:4px 10px;font-size:12px}
.de{font-weight:800;color:#111827}.dp{color:#7c2d12}.sd{color:#14532d}
pre{background:#0b1220;color:#e5e7eb;border-radius:14px;padding:14px;white-space:pre-wrap;overflow:auto}
</style>
</head>
<body>
<header>
  <h1>${this.esc(topic)}</h1>
  <p>Generated by ODIN V03.3 Lesson Generator · ${now}</p>
</header>
<main>
<section>
  <span class="badge">1. Ціль уроку</span>
  <h2>Мета</h2>
  <p>${this.esc(task)}</p>
</section>

<section>
  <span class="badge">2. Підготовка ODIN</span>
  <h2>Session context</h2>
  <p>Урок зібрано на основі вибраних файлів SESSION.</p>
  <ul>${fileList || "<li>SESSION порожня — використано базовий fallback.</li>"}</ul>
</section>

<section>
  <span class="badge">3. Основне правило</span>
  <h2>Правило уроку</h2>
  <p>Цей блок є базовим каркасом. На наступному рівні V03.4 він буде наповнюватись автоматично з вибраних rule/template/translation файлів.</p>
</section>

<section>
  <span class="badge">4. Основні приклади</span>
  <h2>РН / ДП / СД</h2>
  <p class="de">РН: Ich lerne mit ODIN.</p>
  <p class="dp">ДП: Я вчу з ODIN.</p>
  <p class="sd">СД: Я навчаюся за допомогою ODIN.</p>

  <p class="de">РН: Der Unterricht ist klar strukturiert.</p>
  <p class="dp">ДП: Урок є ясно структурований.</p>
  <p class="sd">СД: Урок чітко структурований.</p>
</section>

<section>
  <span class="badge">5. Словник</span>
  <h2>Wortschatz</h2>
  <ul>
    <li>lernen — вчитися</li>
    <li>der Unterricht — урок</li>
    <li>klar — ясно, чітко</li>
    <li>strukturiert — структурований</li>
  </ul>
</section>

<section>
  <span class="badge">6. Практика</span>
  <h2>Übung</h2>
  <p>Переклади українською:</p>
  <ol>
    <li>Ich lerne mit ODIN.</li>
    <li>Der Unterricht ist klar strukturiert.</li>
  </ol>
</section>

<section>
  <span class="badge">7. Домашнє завдання</span>
  <h2>Hausaufgabe</h2>
  <p>Створи 5 власних речень за темою уроку у форматі РН / ДП / СД.</p>
</section>

<section>
  <span class="badge">QA Report</span>
  <h2>${qaStatus}</h2>
  <pre>${this.esc(warnings.length ? warnings.join("\n") : "No critical warnings. EXPORT_READY.")}</pre>
</section>

<section>
  <span class="badge">ODIN Session Groups</span>
  ${sessionBlocks || "<p>No session groups.</p>"}
</section>
</main>
</body>
</html>`;

    document.getElementById("lessonPreview").textContent = this.lastHtml;
    return this.lastHtml;
  },

  download(){
    if(!this.lastHtml) this.generate();
    const topic = (document.getElementById("lessonTopic").value.trim() || "odin_lesson").replace(/[^a-zA-Z0-9_-]+/g, "_");
    const blob = new Blob([this.lastHtml], {type:"text/html;charset=utf-8"});
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = topic + "_ODIN_V03_3_lesson.html";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(a.href);
  },

  async copy(){
    if(!this.lastHtml) this.generate();
    try{
      await navigator.clipboard.writeText(this.lastHtml);
      alert("HTML copied");
    }catch(e){
      alert("Не вдалося скопіювати автоматично. Скопіюй з preview вручну.");
    }
  }
};
