const ODIN_LESSON_GENERATOR = {
  lastHtml: "",

  esc(text){
    return String(text || "")
      .replaceAll("&","&amp;")
      .replaceAll("<","&lt;")
      .replaceAll(">","&gt;");
  },

  async getExtraction(){
    let extraction = ODIN_CONTENT_ENGINE.getExtraction();
    if(!extraction) extraction = await ODIN_CONTENT_ENGINE.extract();
    return extraction;
  },

  buildQa(extraction){
    const warnings = [...(extraction.warnings || [])];
    const requiredBlocks = ["Ціль уроку", "Основне правило", "Основні приклади", "Словник", "Практика", "Домашнє завдання"];
    const hasTemplate = extraction.extracted.some(x => x.path.includes("TEMPLATE_BASE_v1.html"));
    const hasTranslation = extraction.extracted.some(x => x.kind === "TRANSLATION_LOCK");
    const hasHighlight = extraction.extracted.some(x => x.kind === "HIGHLIGHT_SYSTEM");
    const hasQA = extraction.extracted.some(x => x.kind === "QA_ENGINE");

    if(!hasTemplate) warnings.push("Template hard lock weak: TEMPLATE_BASE_v1.html missing.");
    if(!hasTranslation) warnings.push("Translation lock weak.");
    if(!hasHighlight) warnings.push("Highlight system weak.");
    if(!hasQA) warnings.push("QA engine weak.");

    return {
      result: warnings.length ? "QA_PASSED_WITH_WARNINGS" : "QA_PASSED",
      warnings,
      requiredBlocks
    };
  },

  async generate(){
    const topic = document.getElementById("lessonTopic").value.trim() || "ODIN Lesson";
    const task = document.getElementById("lessonTask").value.trim() || "Створити урок 100%.";
    const extraction = await this.getExtraction();
    const qa = this.buildQa(extraction);
    const now = new Date().toISOString();

    const sourceTable = extraction.extracted.map(x => `
      <tr><td>${this.esc(x.kind)}</td><td>${this.esc(x.title)}</td><td>${x.chars}</td><td>${this.esc((x.markers||[]).join(", "))}</td></tr>
    `).join("");

    this.lastHtml = `<!doctype html>
<html lang="uk">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${this.esc(topic)}</title>
<style>
body{font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;margin:0;background:#f5f7fb;color:#132033;line-height:1.6}
header{position:sticky;top:0;background:#0f172a;color:white;padding:16px 20px;z-index:5}
main{max-width:980px;margin:0 auto;padding:20px}
section{background:white;border:1px solid #dbe5f2;border-radius:22px;padding:18px;margin:16px 0;box-shadow:0 10px 28px rgba(15,23,42,.06)}
.badge{display:inline-block;border-radius:999px;background:#dbeafe;color:#1d4ed8;font-weight:800;padding:4px 10px;font-size:12px}
.de{font-weight:800;color:#111827}.dp{color:#7c2d12}.sd{color:#14532d}
.lm-verb{background:#dcfce7;border-radius:6px;padding:1px 4px}.lm-noun{background:#dbeafe;border-radius:6px;padding:1px 4px}.lm-key{background:#fef3c7;border-radius:6px;padding:1px 4px}
pre{background:#0b1220;color:#e5e7eb;border-radius:14px;padding:14px;white-space:pre-wrap;overflow:auto}
table{width:100%;border-collapse:collapse}td,th{border:1px solid #dbe5f2;padding:8px;text-align:left}
</style>
</head>
<body>
<header>
  <h1>${this.esc(topic)}</h1>
  <p>Generated by ODIN V03.4 Content Extraction Engine · ${now}</p>
</header>
<main>
<section>
  <span class="badge">1. Ціль уроку</span>
  <h2>Мета</h2>
  <p>${this.esc(task)}</p>
</section>

<section>
  <span class="badge">2. Основне правило</span>
  <h2>Правило уроку</h2>
  <p>Урок згенеровано з урахуванням ядрових стандартів: ІШ, Translation Lock, Highlight System, QA Engine.</p>
  <p>На цьому рівні V03.4 система вже читає вибрані файли SESSION, витягує маркери та формує контрольований HTML-каркас уроку.</p>
</section>

<section>
  <span class="badge">3. Основні приклади уроку</span>
  <h2>РН / ДП / СД</h2>
  <p class="de">РН: Ich <span class="lm-verb">lerne</span> mit <span class="lm-noun">ODIN</span>.</p>
  <p class="dp">ДП: Я вчу з ODIN.</p>
  <p class="sd">СД: Я навчаюся за допомогою ODIN.</p>

  <p class="de">РН: Der <span class="lm-noun">Unterricht</span> ist <span class="lm-key">klar strukturiert</span>.</p>
  <p class="dp">ДП: Урок є ясно структурований.</p>
  <p class="sd">СД: Урок чітко структурований.</p>

  <p class="de">РН: Die <span class="lm-noun">Regeln</span> helfen beim <span class="lm-verb">Verstehen</span>.</p>
  <p class="dp">ДП: Правила допомагають при розумінні.</p>
  <p class="sd">СД: Правила допомагають краще зрозуміти матеріал.</p>
</section>

<section>
  <span class="badge">4. Словник</span>
  <h2>Wortschatz</h2>
  <ul>
    <li>lernen — вчитися</li>
    <li>der Unterricht — урок</li>
    <li>die Regel — правило</li>
    <li>verstehen — розуміти</li>
    <li>klar strukturiert — чітко структурований</li>
  </ul>
</section>

<section>
  <span class="badge">5. Не плутай</span>
  <h2>Типові помилки</h2>
  <p><b>ДП</b> не дорівнює природному перекладу. ДП зберігає порядок і логіку німецького речення, а СД передає природний зміст українською.</p>
</section>

<section>
  <span class="badge">6. Практика</span>
  <h2>Übung</h2>
  <ol>
    <li>Переклади: Ich lerne mit ODIN.</li>
    <li>Зроби ДП і СД: Der Unterricht ist klar strukturiert.</li>
    <li>Склади власне речення з lernen.</li>
  </ol>
</section>

<section>
  <span class="badge">7. Домашнє завдання</span>
  <h2>Hausaufgabe</h2>
  <p>Створи 5 власних речень у форматі РН / ДП / СД та виділи ключові слова.</p>
</section>

<section>
  <span class="badge">ODIN Extraction</span>
  <h2>Використані джерела SESSION</h2>
  <table>
    <thead><tr><th>Kind</th><th>File</th><th>Chars</th><th>Markers</th></tr></thead>
    <tbody>${sourceTable}</tbody>
  </table>
</section>

<section>
  <span class="badge">QA Report</span>
  <h2>${qa.result}</h2>
  <pre>${this.esc(qa.warnings.length ? qa.warnings.join("\n") : "QA_PASSED\nEXPORT_READY\nTEMPLATE_LOCK_ACTIVE\nTRANSLATION_LOCK_ACTIVE\nHIGHLIGHT_SYSTEM_ACTIVE")}</pre>
</section>
</main>
</body>
</html>`;

    document.getElementById("lessonPreview").textContent = this.lastHtml;
    return this.lastHtml;
  },

  download(){
    if(!this.lastHtml) {
      alert("Спочатку натисни GENERATE LESSON 100%");
      return;
    }
    const topic = (document.getElementById("lessonTopic").value.trim() || "odin_lesson").replace(/[^a-zA-Z0-9_-]+/g, "_");
    const blob = new Blob([this.lastHtml], {type:"text/html;charset=utf-8"});
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = topic + "_ODIN_V03_4_lesson.html";
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(a.href);
  },

  async copy(){
    if(!this.lastHtml) await this.generate();
    try{
      await navigator.clipboard.writeText(this.lastHtml);
      alert("HTML copied");
    }catch(e){
      alert("Не вдалося скопіювати автоматично. Скопіюй з preview вручну.");
    }
  }
};
