const ODIN_SESSION={
 key:"odin_v036_session",
 get(){try{return JSON.parse(localStorage.getItem(this.key))||[]}catch(e){return[]}},
 save(d){localStorage.setItem(this.key,JSON.stringify(d,null,2))},
 add(f){const d=this.get();const rec={title:f.title,path:f.path,type:f.type,layer:f.layer,status:f.status,kind:ODIN_SMART.kind(f),used_at:new Date().toISOString()};if(!d.some(x=>x.path===rec.path))d.push(rec);this.save(d);this.render();return rec},
 addMany(a){a.forEach(f=>this.add(f));this.render()},
 clear(){localStorage.removeItem(this.key);this.render()},
 render(){const el=document.getElementById("sessionList");if(!el)return;const d=this.get();el.innerHTML=d.length?d.map((f,i)=>`<div class="session-item"><b>${i+1}. ${f.title}</b><br><small>${f.kind} · ${f.path}</small></div>`).join(""):"<p class='meta'>Session порожня.</p>"}
};

const ODIN_SMART={
 kind(f){const p=(f.path||"").toLowerCase();if(p.includes("template_base"))return"LESSON_TEMPLATE";if(p.includes("template"))return"ISH/TEMPLATE";if(p.includes("translation")||p.includes("rn_dp_sd"))return"TRANSLATION_LOCK";if(p.includes("highlight")||p.includes("lm_markup"))return"HIGHLIGHT_SYSTEM";if(p.includes("qa"))return"QA_ENGINE";if(p.includes("lesson"))return"LESSON_SYSTEM";if(p.includes("rule")||p.includes("lock"))return"RULE/LOCK";return"DOCUMENT"},
 files(){try{return ODIN_TREE_DATA.flatMap(g=>g.items||[])}catch(e){return[]}},
 autoSelect(){const names=["TEMPLATE_BASE_v1.html","TEMPLATE_RULES.md","TEMPLATE_STRUCTURE.md","TRANSLATION_LOCK.md","RN_DP_SD_STANDARD.md","HIGHLIGHT_SYSTEM_OVERVIEW.md","LM_MARKUP_STANDARD.md","QA_SYSTEM_OVERVIEW.md","QA_STRUCTURE.md","LESSON_STRUCTURE.md"];const files=this.files();const out=[];names.forEach(n=>{const f=files.find(x=>(x.title||"").toLowerCase()===n.toLowerCase());if(f)out.push(f)});ODIN_SESSION.addMany(out);alert("AUTO SELECT CORE: "+out.length+" files")}
};

function initTree(){const t=document.getElementById("tree");t.innerHTML="";let data=[];try{data=ODIN_TREE_DATA}catch(e){}data.forEach(g=>{const hd=document.createElement("div");hd.className="group";hd.textContent=g.group;t.appendChild(hd);(g.items||[]).forEach(f=>{const el=document.createElement("div");el.className="file";el.textContent=f.title;el.onclick=()=>{ODIN_SESSION.add(f);document.getElementById("viewer").innerHTML="<b>"+f.title+"</b><br><small>"+f.path+"</small><p>Added to SESSION.</p>"};t.appendChild(el)})})}

const ODIN_ANALYSIS={
 last:null,
 run(){const topic=document.getElementById("topic").value.trim();const task=document.getElementById("task").value.trim();const mode=document.getElementById("mode").value;const low=(topic+" "+task).toLowerCase();let type="topic";if(low.includes("дієслов")||low.includes("грамат"))type="grammar";if(low.includes("діалог")||low.includes("розмов"))type="dialogue";if(low.includes("фото"))type="photo_task";const level=low.includes("a2")?"A2":low.includes("b1")?"B1":"A1-A2";this.last={topic,task,mode,type,level,blocks:["Ціль","Правило","Живі приклади","Діалог","Словник","Не плутай","Практика","ДЗ","QA"],semantic_rules:["варіації","контекст","рівні складності","природна мова","контроль повторів"],session_files:ODIN_SESSION.get().length};document.getElementById("analysisOut").textContent=JSON.stringify(this.last,null,2);return this.last}
};

const ODIN_GENERATOR={
 html:"",
 esc(s){return String(s||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")},
 examples(mode){let a=[["Ich stehe um sieben Uhr auf.","Я встаю о сьомій годині вгору.","Я встаю о сьомій годині."],["Sie kauft heute im Supermarkt ein.","Вона купує сьогодні в супермаркеті всередину.","Вона сьогодні робить покупки в супермаркеті."],["Wir rufen dich später an.","Ми телефонуємо тобі пізніше до.","Ми зателефонуємо тобі пізніше."],["Mach bitte das Fenster zu.","Роби будь ласка вікно до.","Закрий, будь ласка, вікно."],["Der Kurs fängt um neun Uhr an.","Курс починає о дев’ятій годині на.","Курс починається о дев’ятій."]];if(mode==="STRUCTURED")return a.slice(0,3);if(mode==="HUMAN")a.push(["Ich nehme meine Unterlagen mit.","Я беру мої документи з.","Я беру документи з собою."]);return a},
 dialogue(){return[["A","Wann fängt der Deutschkurs an?","Коли починає німецький курс на?","Коли починається курс німецької?"],["B","Er fängt um neun Uhr an.","Він починає о дев’ятій годині на.","Він починається о дев’ятій."],["A","Bringst du dein Heft mit?","Приносиш ти твій зошит з?","Ти принесеш із собою зошит?"],["B","Ja, ich bringe alles mit.","Так, я приношу все з.","Так, я все візьму з собою."]]},
 generate(){const p=ODIN_ANALYSIS.last||ODIN_ANALYSIS.run();const ex=this.examples(p.mode).map(e=>`<p><b>РН:</b> <span class="hl">${this.esc(e[0])}</span><br><span class="dp">ДП: ${this.esc(e[1])}</span><br><span class="sd">СД: ${this.esc(e[2])}</span></p>`).join("");const dlg=this.dialogue().map(d=>`<p><b>${d[0]}:</b> <span class="hl">${this.esc(d[1])}</span><br><span class="dp">ДП: ${this.esc(d[2])}</span><br><span class="sd">СД: ${this.esc(d[3])}</span></p>`).join("");const qa=`QA_PASSED_WITH_WARNINGS\nІШ blocks: present\nTRANSLATION LOCK: РН/ДП/СД present\nHIGHLIGHT: basic markers present\nMODE: ${p.mode}\nSESSION: ${ODIN_SESSION.get().length}\nWARNING: next layer can deepen real content extraction`;this.html=`<!doctype html><html lang="uk"><head><meta charset="utf-8"><title>${this.esc(p.topic)}</title><style>body{font-family:system-ui;margin:0;background:#f5f7fb;color:#132033;line-height:1.6}header{background:#0f172a;color:white;padding:18px}main{max-width:980px;margin:auto;padding:18px}section{background:white;border:1px solid #dbe5f2;border-radius:20px;padding:16px;margin:14px 0}.badge{background:#dbeafe;color:#1d4ed8;border-radius:99px;padding:4px 10px;font-weight:800}.hl{background:#fef3c7;border-radius:6px;padding:1px 4px}.dp{color:#7c2d12}.sd{color:#14532d}pre{background:#0b1220;color:#e5e7eb;padding:12px;border-radius:12px;white-space:pre-wrap}</style></head><body><header><h1>${this.esc(p.topic)}</h1><p>ODIN V03.6 · ${p.mode} · ${p.level}</p></header><main><section><span class="badge">1. Ціль уроку</span><h2>Мета</h2><p>${this.esc(p.task)}</p></section><section><span class="badge">2. Основне правило</span><h2>Пояснення</h2><p>У відокремлюваних дієсловах префікс часто переходить у кінець речення. Учень має бачити конструкцію як єдине ціле.</p></section><section><span class="badge">3. Живі приклади</span>${ex}</section><section><span class="badge">4. Діалог</span>${dlg}</section><section><span class="badge">5. Словник</span><ul><li>anfangen — починати</li><li>mitbringen — приносити з собою</li><li>zumachen — закривати</li><li>anrufen — телефонувати</li><li>einkaufen — робити покупки</li></ul></section><section><span class="badge">6. Не плутай</span><p>Не шукай префікс тільки біля дієслова: у простому реченні він часто стоїть у кінці.</p></section><section><span class="badge">7. Практика</span><ol><li>Знайди префікс.</li><li>Зроби ДП і СД.</li><li>Склади 5 власних речень.</li></ol></section><section><span class="badge">8. Домашнє завдання</span><p>Напиши міні-діалог на 6 реплік із трьома відокремлюваними дієсловами.</p></section><section><span class="badge">QA Report</span><pre>${this.esc(qa)}</pre></section></main></body></html>`;document.getElementById("out").textContent=this.html},
 download(){if(!this.html)this.generate();const b=new Blob([this.html],{type:"text/html;charset=utf-8"});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="ODIN_V03_6_deep_lesson.html";a.click();URL.revokeObjectURL(a.href)}
};
document.addEventListener("DOMContentLoaded",()=>{initTree();ODIN_SESSION.render()});
