let CURRENT_HTML="", CURRENT_META=null;
const SKEY="odin_v041_session", LKEY="odin_v041_lessons";
function uid(){return"lesson_"+Date.now()+"_"+Math.random().toString(16).slice(2)}
function esc(s){return String(s||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;")}
function fn(s){return String(s||"lesson").replace(/[^a-zA-Z0-9А-Яа-яЇїІіЄєҐґ_-]+/g,"_").slice(0,70)}
function getSession(){try{return JSON.parse(localStorage.getItem(SKEY))||[]}catch(e){return[]}}
function saveSession(d){localStorage.setItem(SKEY,JSON.stringify(d,null,2));renderSession()}
function kind(f){const p=(f.path||"").toLowerCase();if(p.includes("template_base"))return"LESSON_TEMPLATE";if(p.includes("template"))return"ISH/TEMPLATE";if(p.includes("translation")||p.includes("rn_dp_sd"))return"TRANSLATION_LOCK";if(p.includes("highlight")||p.includes("lm_markup"))return"HIGHLIGHT_SYSTEM";if(p.includes("qa"))return"QA_ENGINE";if(p.includes("lesson"))return"LESSON_SYSTEM";if(p.includes("rule")||p.includes("lock"))return"RULE/LOCK";return"DOCUMENT"}
function addSession(f){const d=getSession();const r={title:f.title,path:f.path,type:f.type,layer:f.layer,status:f.status,kind:kind(f),used_at:new Date().toISOString()};if(!d.some(x=>x.path===r.path))d.push(r);saveSession(d)}
function clearSession(){localStorage.removeItem(SKEY);renderSession()}
function renderSession(){const el=document.getElementById("sessionList");if(!el)return;const d=getSession();el.innerHTML=d.length?d.map((f,i)=>`<div class="item"><b>${i+1}. ${esc(f.title)}</b><br><small>${esc(f.kind)} · ${esc(f.path)}</small></div>`).join(""):"<p class='meta'>Session порожня.</p>"}
function files(){try{return ODIN_TREE_DATA.flatMap(g=>g.items||[])}catch(e){return[]}}
function autoSelect(){const names=["TEMPLATE_BASE_v1.html","TEMPLATE_RULES.md","TRANSLATION_LOCK.md","RN_DP_SD_STANDARD.md","HIGHLIGHT_SYSTEM_OVERVIEW.md","QA_SYSTEM_OVERVIEW.md","LESSON_STRUCTURE.md"];const all=files();let count=0;names.forEach(n=>{const f=all.find(x=>(x.title||"").toLowerCase()===n.toLowerCase());if(f){addSession(f);count++}});alert("AUTO SELECT CORE: "+count)}
function initTree(){const t=document.getElementById("tree");let data=[];try{data=ODIN_TREE_DATA}catch(e){}t.innerHTML="";data.forEach(g=>{const h=document.createElement("div");h.className="group";h.textContent=g.group;t.appendChild(h);(g.items||[]).forEach(f=>{const e=document.createElement("div");e.className="file";e.textContent=f.title;e.onclick=()=>{addSession(f);document.getElementById("viewer").innerHTML="<b>"+esc(f.title)+"</b><br><small>"+esc(f.path)+"</small><p>Added to SESSION.</p>"};t.appendChild(e)})})}
function examples(mode){let a=[["Ich stehe um sieben Uhr auf.","Я встаю о сьомій годині вгору.","Я встаю о сьомій годині."],["Sie kauft heute im Supermarkt ein.","Вона купує сьогодні в супермаркеті всередину.","Вона сьогодні робить покупки в супермаркеті."],["Wir rufen dich später an.","Ми телефонуємо тобі пізніше до.","Ми зателефонуємо тобі пізніше."],["Mach bitte das Fenster zu.","Роби будь ласка вікно до.","Закрий, будь ласка, вікно."],["Der Kurs fängt um neun Uhr an.","Курс починає о дев’ятій годині на.","Курс починається о дев’ятій."]];if(mode==="STRUCTURED")return a.slice(0,3);if(mode==="HUMAN")a.push(["Ich nehme meine Unterlagen mit.","Я беру мої документи з.","Я беру документи з собою."]);return a}
function generateLesson(){const topic=document.getElementById("topic").value.trim();const task=document.getElementById("task").value.trim();const mode=document.getElementById("mode").value;const session=getSession();const ex=examples(mode).map(e=>`<p><b>РН:</b> <span class="hl">${esc(e[0])}</span><br><span class="dp">ДП: ${esc(e[1])}</span><br><span class="sd">СД: ${esc(e[2])}</span></p>`).join("");const qa=`QA_PASSED_WITH_WARNINGS\nІШ blocks: present\nTRANSLATION LOCK: РН/ДП/СД present\nHIGHLIGHT: basic markers present\nMODE: ${mode}\nSESSION: ${session.length}\nEXPORT: HTML + JSON supported`;CURRENT_META={id:uid(),title:topic,mode,type:"LESSON_FROM_TOPIC",level:"A1-A2",qa,session,created_at:new Date().toISOString()};CURRENT_HTML=`<!doctype html><html lang="uk"><head><meta charset="utf-8"><title>${esc(topic)}</title><style>body{font-family:system-ui;margin:0;background:#f5f7fb;color:#132033;line-height:1.6}header{background:#0f172a;color:white;padding:18px}main{max-width:980px;margin:auto;padding:18px}section{background:white;border:1px solid #dbe5f2;border-radius:20px;padding:16px;margin:14px 0}.badge{background:#dbeafe;color:#1d4ed8;border-radius:99px;padding:4px 10px;font-weight:800}.hl{background:#fef3c7;border-radius:6px;padding:1px 4px}.dp{color:#7c2d12}.sd{color:#14532d}pre{background:#0b1220;color:#e5e7eb;padding:12px;border-radius:12px;white-space:pre-wrap}</style></head><body><header><h1>${esc(topic)}</h1><p>ODIN V04.1 · ${mode}</p></header><main><section><span class="badge">1. Ціль уроку</span><h2>Мета</h2><p>${esc(task)}</p></section><section><span class="badge">2. Основне правило</span><p>У відокремлюваних дієсловах префікс часто переходить у кінець речення. Учень має бачити конструкцію як єдине ціле.</p></section><section><span class="badge">3. Живі приклади</span>${ex}</section><section><span class="badge">4. Діалог</span><p><b>A:</b> Wann fängt der Deutschkurs an?<br><span class="dp">ДП: Коли починає німецький курс на?</span><br><span class="sd">СД: Коли починається курс німецької?</span></p><p><b>B:</b> Er fängt um neun Uhr an.<br><span class="dp">ДП: Він починає о дев’ятій годині на.</span><br><span class="sd">СД: Він починається о дев’ятій.</span></p></section><section><span class="badge">5. Словник</span><ul><li>anfangen — починати</li><li>mitbringen — приносити з собою</li><li>zumachen — закривати</li><li>anrufen — телефонувати</li></ul></section><section><span class="badge">6. Практика</span><ol><li>Знайди префікс.</li><li>Зроби ДП і СД.</li><li>Склади 5 речень.</li></ol></section><section><span class="badge">7. Домашнє завдання</span><p>Напиши міні-діалог на 6 реплік із трьома відокремлюваними дієсловами.</p></section><section><span class="badge">QA Report</span><pre>${esc(qa)}</pre></section></main></body></html>`;document.getElementById("out").textContent=CURRENT_HTML;return CURRENT_HTML}
function blobDownload(text,name,type){const b=new Blob([text],{type});const a=document.createElement("a");a.href=URL.createObjectURL(b);a.download=name;a.click();URL.revokeObjectURL(a.href)}
function downloadHtml(){if(!CURRENT_HTML)generateLesson();blobDownload(CURRENT_HTML,fn(CURRENT_META.title)+"_lesson.html","text/html;charset=utf-8")}
function getLessons(){try{return JSON.parse(localStorage.getItem(LKEY))||[]}catch(e){return[]}}
function saveLessons(d){localStorage.setItem(LKEY,JSON.stringify(d,null,2));renderLessons()}
function saveLesson(){if(!CURRENT_HTML)generateLesson();const d=getLessons();const lesson={...CURRENT_META,html:CURRENT_HTML,updated_at:new Date().toISOString()};d.unshift(lesson);saveLessons(d);alert("LESSON SAVED")}
function loadLesson(id){const l=getLessons().find(x=>x.id===id);if(!l)return;CURRENT_META=l;CURRENT_HTML=l.html;document.getElementById("topic").value=l.title;document.getElementById("mode").value=l.mode||"HYBRID";document.getElementById("out").textContent=l.html}
function deleteLesson(id){if(!confirm("Delete lesson?"))return;saveLessons(getLessons().filter(x=>x.id!==id))}
function clearLessons(){if(!confirm("Clear all lessons?"))return;localStorage.removeItem(LKEY);renderLessons()}
function exportLessonJson(id){const l=getLessons().find(x=>x.id===id);if(l)blobDownload(JSON.stringify(l,null,2),fn(l.title)+"_lesson.json","application/json;charset=utf-8")}
function exportCurrentJson(){if(!CURRENT_HTML)generateLesson();blobDownload(JSON.stringify({meta:CURRENT_META,html:CURRENT_HTML},null,2),fn(CURRENT_META.title)+"_lesson.json","application/json;charset=utf-8")}
function renderLessons(){const el=document.getElementById("libraryList");if(!el)return;const d=getLessons();el.innerHTML=d.length?d.map((l,i)=>`<div class="item"><b>${i+1}. ${esc(l.title)}</b><br><span class="meta">${esc(l.mode)} · ${esc(l.level)} · ${esc(l.type)}</span><br><small>${esc(l.created_at)}</small><div class="actions"><button onclick="loadLesson('${l.id}')">LOAD</button><button class="blue" onclick="exportLessonJson('${l.id}')">EXPORT JSON</button><button class="red" onclick="deleteLesson('${l.id}')">DELETE</button></div></div>`).join(""):"<p class='meta'>Уроків ще немає.</p>"}
document.addEventListener("DOMContentLoaded",()=>{initTree();renderSession();renderLessons()});
